In [ ]:
# 1. pick a song by name
# 2. get that song's feature vector
# 3. compute cosine similarity between it and every other song
# 4. sort and return the top 10 most similar songs

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
import sys
sys.path.append("../src")
from recommender import build_taste_profile, recommend_from_profile
from data_prep import clean_audio_dataset, build_catalog, add_genre_label

In [5]:
catalog = pd.read_csv("../data/processed/full_catalog.csv")
my_songs = pd.read_csv("../data/processed/my_matched_songs.csv")

print("catalog (combined):", catalog.shape)
print("my matched songs:", my_songs.shape)

catalog (combined): (121923, 15)
my matched songs: (247, 21)

In [6]:
features = ["danceability", "energy", "loudness", "speechiness",
            "acousticness", "instrumentalness", "liveness",
            "valence", "tempo"]

X = StandardScaler().fit_transform(catalog[features])

In [7]:
def recommend_similar(song_name, n=10, mode="mixed"):
    matches = catalog[catalog["track_name"].str.lower() == song_name.lower()]
    if matches.empty:
        print("Song not found. Try another name.")
        return None
    idx = matches.index[0]
    group = catalog.loc[idx, "genre_or_language"]

    song_vector = X[idx].reshape(1, -1)
    similarities = cosine_similarity(song_vector, X).flatten()

    scores = similarities.copy()

    if mode == "same_group":
        mask = (catalog["genre_or_language"] == group).values
        scores = scores * mask
    elif mode == "boosted":
        mask = (catalog["genre_or_language"] == group).values
        scores = scores + (mask * 0.05)

    sorted_indices = scores.argsort()[::-1]
    sorted_indices = [i for i in sorted_indices if i != idx][:n]

    results = catalog.iloc[sorted_indices][["track_name", "artists", "genre_or_language", "label_type"]].copy()
    results["similarity"] = similarities[sorted_indices]
    return results

In [ ]:
display(recommend_similar("Aahista", mode="boosted"))
print("\nSame group only:")
display(recommend_similar("Aahista", mode="same_group"))

,track_name,artists,genre_or_language,label_type,similarity
84885,Ve Kamleya - Chill Beats,"Arijit Singh, Shreya Ghoshal, Altamash Faridi,...",Hindi,language,0.961611
90773,Maari Maavadi,"Amit Trivedi, Osman Mir, Aamir Mir",Hindi,language,0.959774
116778,Valentine Mashup 2022,"Armaan Malik, Pritam, Arijit Singh, Sachin-Jig...",Hindi,language,0.958445
90188,"Alvida (From ""Life in a Metro"")","Pritam, KK",Hindi,language,0.951831
89718,Alvida,"Pritam, KK",Hindi,language,0.951172
92791,Love Mashup 2018,"Amitabh Bhattacharya, Atif Aslam, Shreya Ghosh...",Hindi,language,0.949137
89931,"Tur Kalleyan (From ""Laal Singh Chaddha"") [TAMIL]","Pritam, Shadab Faridi, Altamash Faridi, Sreera...",Hindi,language,0.947711
116638,Sun Saathiya - Lofi Mix by L3AD,"Sachin-Jigar, Priya Saraiya, Divya Kumar",Hindi,language,0.945419
116539,Valentine's Day Mashup - DJ Basque,"Sadhana Sargam, Udit Narayan, Dj Basque, Ariji...",Hindi,language,0.941923
86165,Se Chole Gechhe,Javed Ali,Hindi,language,0.935172

Same group only:

,track_name,artists,genre_or_language,label_type,similarity
84885,Ve Kamleya - Chill Beats,"Arijit Singh, Shreya Ghoshal, Altamash Faridi,...",Hindi,language,0.961611
90773,Maari Maavadi,"Amit Trivedi, Osman Mir, Aamir Mir",Hindi,language,0.959774
116778,Valentine Mashup 2022,"Armaan Malik, Pritam, Arijit Singh, Sachin-Jig...",Hindi,language,0.958445
90188,"Alvida (From ""Life in a Metro"")","Pritam, KK",Hindi,language,0.951831
89718,Alvida,"Pritam, KK",Hindi,language,0.951172
92791,Love Mashup 2018,"Amitabh Bhattacharya, Atif Aslam, Shreya Ghosh...",Hindi,language,0.949137
89931,"Tur Kalleyan (From ""Laal Singh Chaddha"") [TAMIL]","Pritam, Shadab Faridi, Altamash Faridi, Sreera...",Hindi,language,0.947711
116638,Sun Saathiya - Lofi Mix by L3AD,"Sachin-Jigar, Priya Saraiya, Divya Kumar",Hindi,language,0.945419
116539,Valentine's Day Mashup - DJ Basque,"Sadhana Sargam, Udit Narayan, Dj Basque, Ariji...",Hindi,language,0.941923
86165,Se Chole Gechhe,Javed Ali,Hindi,language,0.935172

In [9]:
# fit a scaler on the catalog (needed for the profile recommender)
catalog_scaler = StandardScaler().fit(catalog[features])

# build your taste profile from your top loved songs
my_profile = build_taste_profile(my_songs, features, top_n=30)
print(my_profile)

danceability          0.548033
energy                0.483300
loudness             -8.003833
speechiness           0.048933
acousticness          0.614420
instrumentalness      0.000362
liveness              0.144207
valence               0.411900
tempo               109.431600
dtype: float64

In [11]:
already_have = set(my_songs["track"])

my_recommendations = recommend_from_profile(
    profile=my_profile,
    catalog=catalog,
    features=features,
    scaler=catalog_scaler,
    already_have=already_have,
    n=15
)

my_recommendations[["track_name", "artists", "similarity"]]

/home/home/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

,track_name,artists,similarity
16459,Beautiful Crazy,Luke Combs,0.984165
16602,From Austin,Zach Bryan,0.974995
117140,No Plastic Swear Now,"Leila Kaiyr, Devan Ekambaram",0.973317
82921,Cadbury Penne - Sleep Lofi,"G. V. Prakash, Karthik Mano, Jeruson",0.971989
43831,Hariye Jawar Gaan,Anupam Roy,0.970972
26204,Nothing For Christmas,New Found Glory,0.969562
7806,Guarda Tua Fé (Ao Vivo Em Los Angeles),Aline Barros,0.969150
76030,Mano a Mano,Lidia Borda,0.968880
51382,Kannetha Dooratholam,Sachin Warrier,0.967871
59621,Saagar Jaisi Aankhonwali - Saagar / Soundtrack...,Kishore Kumar,0.967869
20707,Hard Candy Christmas,Cyndi Lauper,0.967842
5812,When A Heart Breaks,The Steeldrivers,0.967837
51470,Vava Mulle Vava Melle,Sajeer Koppam;Nysha Fathima,0.966383
121524,Vaazh Veesum,Anirudh Ravichander,0.966311
64412,Si Nos Dejan,Alberto Vazquez;Manolo Muñoz,0.965765